services:
  janus-gateway:
    image: yykim/janus-gateway
    container_name: janus-gateway
    ports:
      - '8086:8086' # nginx
      - '7088:7088' # janus http admin api
      - '7889:7889' # janus https admin api
      - '8088:8088' # janus http api
      - '8089:8089' # janus https api
      - '8188:8188' # janus websocket
      - '8989:8989' # janus secure websocket
      - '7989:7989' # janus websocket admin
      - '7188:7188' # janus secure websocket admin
      - '20000-20200:20000-20200/udp' # rtp port range
    # environment:
    # network_mode: 'host'
    volumes:
      - './config/nginx.conf:/etc/nginx/nginx.conf'
      - './cert/cert.pem:/etc/nginx/cert.pem'
      - './cert/key.pem:/etc/nginx/key.pem'
      - './config/janus.jcfg:/usr/local/etc/janus/janus.jcfg'
      - './config/janus.transport.http.jcfg:/usr/local/etc/janus/janus.transport.http.jcfg'
      - './config/janus.transport.websockets.jcfg:/usr/local/etc/janus/janus.transport.websockets.jcfg'
      - './config/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg'
      - './config/janus.eventhandler.wsevh.jcfg:/usr/local/etc/janus/janus.eventhandler.wsevh.jcfg'
      - './cert/cert.pem:/usr/local/etc/janus/cert.pem'
      - './cert/key.pem:/usr/local/etc/janus/key.pem'
# docker run -it -p 8086:8086 -p 8188:8188 -p 8088:8088 yykim/janus-gateway

