version: '3'
services:
  janus-gateway:
    image: yykim/janus-gateway
    container_name: janus-gateway
    ports:
      - '8086:8086' # nginx
      - '8088:8088' # janus http
      - '8188:8188' # janus websocket
    # environment:
    # network_mode: 'host'
    volumes:
      # - './config/janus.transport.http.jcfg:/usr/local/etc/janus/janus.transport.http.jcfg'
      # - './config/janus.jcfg:/usr/local/etc/janus/janus.jcfg'
      # - './config/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg'
      - './config/nginx.conf:/etc/nginx/nginx.conf'
# docker run -it -p 8086:8086 -p 8188:8188 -p 8088:8088 yykim/janus-gateway
